### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Grunt#1]
- [x] dodalem pare uwag w komentarzach do commita: https://github.com/JoannaKu/Grunt/commit/2c2cf36eef97d61cd9f4084d0fc10d48604dcee7
- [x] brakuje pliku sass, ktory bylby przerabiany na css - jesli nie masz sassa do tego projektu, to uzyj innego
- [x] brakuje obrazkow, ktore bylyby przerabiane taskiem `imagemin`

**Comment by michal-bootcamp** [comment]
poprawilem Gruntfile, byla zla sciezka do obrazkow, poniewaz on korzysta z tego:
`cwd: 'images/',` i potem szuka wewnatrz plikow `src: ['*.{png,jpg,gif}'],`

wczesniej bylo tak, ze szukal obrazkow w `images/images/*.{png,jpg,gif}`

teraz popraw html i css zeby korzystaly z obrazkow z katalogu `build`

**Comment by JoannaKu** [comment]
poprawione :) zmieniam zdanie, grunt jest jednak przydatny :)

**Comment by michal-bootcamp** [comment]
no to super :) zostal jeszcze do podmiany obrazek w html w linii 21 i poprosze zebys nie uzywala polskich znakow w nazwach plikow, czyli tutaj w nazwach obrazkow

**Comment by JoannaKu** [comment]
ok, poprawione :)
